const String letter1 = ""
    "It may not be improper in the first place to inform your Readers, that I intend once a "
    "\t"
    "Fortnight to present them, by the Help of this Paper, with a short Epistle, which I presume "
    "\t"
    "will add somewhat to their Entertainment."
    "\n"
    "And since it is observed, that the Generality of People, now a days, are unwilling either to "
    "\t"
    "commend or dispraise what they read, until they are in some measure informed who or "
    "\t"
    "what the Author of it is, whether he be poor or rich, old or young, a Schollar or a Leather "
    "\t"
    "Apron Man, &c. and give their Opinion of the Performance, according to the Knowledge "
    "\t"
    "which they have of the Author\'s Circumstances, it may not be amiss to begin with a short "
    "\t"
    "Account of my past Life and present Condition, that the Reader may not be at a Loss to "
    "\t"
    "judge whether or no my Lucubrations are worth his reading."
    "\n"
    "At the time of my Birth, my Parents were on Ship-board in their Way from London to N. "
    "\t"
    "England. My Entrance into this troublesome World was attended with the Death of my "
    "\t"
    "Father, a Misfortune, which tho\' I was not then capable of knowing, I shall never be able to"
    "\t"
    " forget; for as he, poor Man, stood upon the Deck rejoycing at my Birth, a merciless Wave "
    "\t"
    "entred the Ship, and in one Moment carry\'d him beyond Reprieve. Thus, was the first "
    "\t"
    "Day which I saw, the last that was seen by my Father; and thus was my disconsolate "
    "\t"
    "Mother at once made both a Parent and a Widow."
    "\n"
    "When we arrived at Boston (which was not long after) I was put to Nurse in a Country "
    "\t"
    "Place, at a small Distance from the Town, where I went to School, and past my Infancy "
    "\t"
    "and Childhood in Vanity and Idleness, until I was bound out Apprentice, that I might no "
    "\t"
    "longer be a Charge to my Indigent Mother, who was put to hard Shifts for a Living."
    "\n"
    "My Master was a Country Minister, a pious good-natur\'d young Man, and a Batchelor: he "
    "\t"
    "labour\'d with all his Might to instil vertuous and godly Principles into my tender Soul, well "
    "\t"
    "knowing that it was the most suitable Time to make deep and lasting Impressions on the "
    "\t"
    "Mind, while it was yet untainted with Vice, free and unbiass\'d. He endeavour\'d that I might "
    "\t"
    "be instructed in all that Knowledge and Learning which is necessary for our Sex, and "
    "\t"
    "deny\'d me no Accomplishment that could possibly be attained in a Country Place; such as "
    "\t"
    "all Sorts of Needle-Work, Writing, Arithmetick, &c. and observing that I took a more than "
    "\t"
    "ordinary Delight in reading ingenious Books, he gave me the free Use of his Library, which "
    "\t"
    "tho\' it was but small, yet it was well chose, to inform the Understanding rightly, and enable "
    "\t"
    "the Mind to frame great and noble Ideas."
    "\n"
    "Before I had liv\'d quite two Years with this Reverend Gentleman, my indulgent Mother "
    "\t"
    "departed this Life, leaving me as it were by my self, having no Relation on Earth within my "
    "\t"
    "Knowledge."
    "\n"
    "I will not abuse your Patience with a tedious Recital of all the frivolous Accidents of my "
    "\t"
    "Life, that happened from this Time until I arrived to Years of Discretion, only inform you "
    "\t"
    "that I liv\'d a chearful Country Life, spending my leisure Time either in some innocent "
    "\t"
    "Diversion with the neighbouring Females, or in some shady Retirement, with the best of "
    "\t"
    "Company, Books. Thus I past away the Time with a Mixture of Profit and Pleasure, having "
    "\t"
    "no affliction but what was imaginary, and created in my own Fancy; as nothing is more "
    "\t"
    "common with us Women, than to be grieving for nothing, when we have nothing else to "
    "\t"
    "grieve for."
    "\n"
    "As I would not engross too much of your Paper at once, I will defer the Remainder of my "
    "\t"
    "Story until my next Letter; in the mean time desiring your Readers to exercise their "
    "\t"
    "Patience, and bear with my Humours now and then, because I shall trouble them but "
    "\t"
    "seldom. I am not insensible of the Impossibility of pleasing all, but I would not willingly "
    "\t"
    "displease any; and for those who will take Offence were none is intended, they are "
    "\t"
    "beneath the Notice of Your Humble Servant,";

const String letter2 = ""
    "Histories of Lives are seldom entertaining, unless they contain something either admirable "
    "\t"
    "or exemplar: And since there is little or nothing of this Nature in my own Adventures, I will "
    "\t"
    "not tire your Readers with tedious Particulars of no Consequence, but will briefly, and in as "
    "\t"
    "few Words as possible, relate the most material Occurrences of my Life, and according to "
    "\t"
    "my Promise, confine all to this Letter."
    "\n"
    "My Reverend master who had hitherto remained a Batchelor, (after much meditation on "
    "\t"
    "the Eighteenth verse of the Second Chapter of Genesis,) took up a Resolution to marry; "
    "\t"
    "and having made several unsuccessful fruitless Attempts on the more topping Sort of our "
    "\t"
    "Sex, and being tir\'d with making troublesome Journeys and Visits to no Purpose, he began "
    "\t"
    "unexpectedly to cast a loving Eye upon Me, whom he had brought up cleverly to his Hand."
    "\n"
    "There is certainly scarce any Part of a Man\'s Life in which he appears more silly and "
    "\t"
    "ridiculous, than when he makes his first Onset in Courtship. The aukward Manner in which "
    "\t"
    "my Master first discover\'d his Intentions, made me, in spite of my Reverence to his "
    "\t"
    "Person, burst out into an unmannerly Laughter: However, having ask\'d his Pardon, and "
    "\t"
    "with much ado compos\'d my Countenance, I promis\'d him I would take his Proposal into "
    "\t"
    "serious Consideration, and speedily give him an Answer."
    "\n"
    "As he had been a great Benefactor (and in a Manner a Father to me) I could not well deny "
    "\t"
    "his Request, when I once perceived he was in earnest. Whether it was Love, or Gratitude, "
    "\t"
    "or Pride, or all Three that made me consent, I know not; but it is certain, he found it no "
    "\t"
    "hard Matter, by the Help of his Rhetorick, to conquer my Heart, and perswade me to marry "
    "\t"
    "him."
    "\n"
    "This unexpected Match was very astonishing to all the Country round about, and served to "
    "\t"
    "furnish them with Discourse for a long Time after; some approving it, others disliking it, as "
    "\t"
    "they were led by their various Fancies and Inclinations."
    "\n"
    "We lived happily together in the Heighth of conjugal Love and mutual Endearments, for "
    "\t"
    "near Seven Years, in which Time we added Two likely Girls and a Boy to the Family of the "
    "\t"
    "Dogoods: But alas! When my Sun was in its meridian Altitude, inexorable unrelenting "
    "\t"
    "Death, as if he had envy\'d my Happiness and Tranquility, and resolv\'d to make me entirely "
    "\t"
    "miserable by the Loss of so good an Husband, hastened his Flight to the Heavenly World, "
    "\t"
    "by a sudden unexpected Departure from this."
    "\n"
    "I have now remained in a State of Widowhood for several Years, but it is a State I never "
    "\t"
    "much admir\'d, and I am apt to fancy that I could be easily perswaded to marry again, "
    "\t"
    "provided I was sure of a good-humour\'d, sober, agreeable Companion: But one, even with "
    "\t"
    "these few good Qualities, being hard to find, I have lately relinquish\'d all Thoughts of that "
    "\t"
    "Nature."
    "\n"
    "At present I pass away my leisure Hours in Conversation, either with my honest Neighbour "
    "\t"
    "Rusticus and his Family, or with the ingenious Minister of our Town, who now lodges at my "
    "\t"
    "House, and by whose Assistance I intend now and then to beautify my Writings with a "
    "\t"
    "Sentence or two in the learned Languages, which will not only be fashionable, and "
    "\t"
    "pleasing to those who do not understand it, but will likewise be very ornamental."
    "\n"
    "I shall conclude this with my own Character, which (one would think) I should be best able "
    "\t"
    "to give. Know then, That I am an Enemy to Vice, and a Friend to Vertue. I am one of an "
    "\t"
    "extensive Charity, and a great Forgiver of private Injuries: A hearty Lover of the Clergy and "
    "\t"
    "all good Men, and a mortal Enemy to arbitrary Government and unlimited Power. I am "
    "\t"
    "naturally very jealous for the Rights and Liberties of my Country; and the least appearance "
    "\t"
    "of an Incroachment on those invaluable Priviledges, is apt to make my Blood boil "
    "\t"
    "exceedingly. I have likewise a natural Inclination to observe and reprove the Faults of "
    "\t"
    "others, at which I have an excellent Faculty. I speak this by Way of Warning to all such "
    "\t"
    "whose Offences shall come under my Cognizance, for I never intend to wrap my Talent in "
    "\t"
    "a Napkin. To be brief; I am courteous and affable, good humour\'d (unless I am first "
    "\t"
    "provok\'d,) and handsome, and sometimes witty, but always, Sir, Your Friend and Humble "
    "\t"
    "Servant,";

const String letter3 = ""
    "It is undoubtedly the Duty of all Persons to serve the Country they live in, according to "
    "\t"
    "their Abilities; yet I sincerely acknowledge, that I have hitherto been very deficient in this "
    "\t"
    "Particular; whether it was for want of Will or Opportunity, I will not at present stand to "
    "\t"
    "determine: Let it suffice, that I now take up a Resolution, to do for the future all that lies in "
    "\t"
    "my Way for the Service of my Countrymen."
    "\n"
    "I have from my Youth been indefatigably studious to gain and treasure up in my Mind all "
    "\t"
    "useful and desireable Knowledge, especially such as tends to improve the Mind, and "
    "\t"
    "enlarge the Understanding: And as I have found it very beneficial to me, I am not without "
    "\t"
    "Hopes, that communicating my small Stock in this Manner, by Peace-meal to the Publick, "
    "\t"
    "may be at least in some Measure useful."
    "\n"
    "I am very sensible that it is impossible for me, or indeed any one Writer to "
    "\t"
    "please all Readers at once. Various Persons have different Sentiments; and that which is "
    "\t"
    "pleasant and delightful to one, gives another a Disgust. He that would (in this Way of "
    "\t"
    "Writing) please all, is under a Necessity to make his Themes almost as numerous as his "
    "\t"
    "Letters. He must one while be merry and diverting, then more solid and serious; one while "
    "\t"
    "sharp and satyrical, then (to mollify that) be sober and religious; at one Time let the "
    "\t"
    "Subject be Politicks, then let the next Theme be Love: Thus will every one, one Time or "
    "\t"
    "other find some thing agreeable to his own Fancy, and in his Turn be delighted."
    "\n"
    "According to this Method I intend to proceed, bestowing now and then a few gentle "
    "\t"
    "Reproofs on those who deserve them, not forgetting at the same time to applaud those "
    "\t"
    "whose Actions merit Commendation. And here I must not forget to invite the ingenious "
    "\t"
    "Part of your Readers, particularly those of my own Sex to enter into a Correspondence "
    "\t"
    "with me, assuring them, that their Condescension in this Particular shall be received as a "
    "\t"
    "Favour, and accordingly acknowledged."
    "\n"
    "I think I have now finish\'d the Foundation, and I intend in my next to begin to raise the "
    "\t"
    "Building. Having nothing more to write at present, I must make the usual excuse in such "
    "\t"
    "Cases, of being in haste, assuring you that I speak from my Heart when I call my self, The "
    "\t"
    "most humble and obedient of all the Servants your Merits have acquir\'d,";

const String letter4 = ""
    "Discoursing the other Day at Dinner with my Reverend Boarder, formerly mention\'d, "
    "\t"
    "(whom for Distinction sake we will call by the Name of Clericus,) concerning the Education "
    "\t"
    "of Children, I ask\'d his Advice about my young Son William, whether or no I had best "
    "\t"
    "bestow upon him Academical Learning, or (as our Phrase is) bring him up at our College: "
    "\t"
    "He perswaded me to do it by all Means, using many weighty Arguments with me, and "
    "\t"
    "answering all the Objections that I could form against it; telling me withal, that he did not "
    "\t"
    "doubt but that the Lad would take his Learning very well, and not idle away his Time as too "
    "\t"
    "many there now-a-days do. These Words of Clericus gave me a Curiosity to inquire a little "
    "\t"
    "more strictly into the present Circumstances of that famous Seminary of Learning; but the "
    "\t"
    "Information which he gave me, was neither pleasant, nor such as I expected."
    "\n"
    "As soon as Dinner was over, I took a solitary Walk into my Orchard, still ruminating on "
    "\t"
    "Clericus\'s Discourse with much Consideration, until I came to my usual Place of "
    "\t"
    "Retirement under the Great Apple-Tree; where having seated my self, and carelessly laid "
    "\t"
    "my Head on a verdant Bank, I fell by Degrees into a soft and undisturbed Slumber. My "
    "\t"
    "waking Thoughts remained with me in my Sleep, and before I awak\'d again, I dreamt the "
    "\t"
    "following Dream."
    "\n"
    "I fancy\'d I was travelling over pleasant and delightful Fields and Meadows, and thro\' many "
    "\t"
    "small Country Towns and Villages; and as I pass\'d along, all Places resounded with the "
    "\t"
    "Fame of the Temple of Learning: Every Peasant, who had wherewithal, was preparing to "
    "\t"
    "send one of his Children at least to this famous Place; and in this Case most of them "
    "\t"
    "consulted their own Purses instead of their Childrens Capacities: So that I observed, a "
    "\t"
    "great many, yea, the most part of those who were travelling thither, were little better than "
    "\t"
    "Dunces and Blockheads. Alas! alas!"
    "\n"
    "At length I entred upon a spacious Plain, in the Midst of which was erected a large and "
    "\t"
    "stately Edifice: It was to this that a great Company of Youths from all Parts of the Country "
    "\t"
    "were going; so stepping in among the Crowd, I passed on with them, and presently arrived "
    "\t"
    "at the Gate."
    "\n"
    "The Passage was kept by two sturdy Porters named Riches and Poverty, and the latter "
    "\t"
    "obstinately refused to give Entrance to any who had not first gain\'d the Favour of the "
    "\t"
    "former; so that I observed, many who came even to the very Gate, were obliged to travel "
    "\t"
    "back again as ignorant as they came, for want of this necessary Qualification. However, as "
    "\t"
    "a Spectator I gain\'d Admittance, and with the rest entred directly into the Temple."
    "\n"
    "In the Middle of the great Hall stood a stately and magnificent Throne, which was "
    "\t"
    "ascended to by two high and difficult Steps. On the Top of it sat Learning in awful State; "
    "\t"
    "she was apparelled wholly in Black, and surrounded almost on every Side with "
    "\t"
    "innumerable Volumes in all Languages. She seem\'d very busily employ\'d in writing "
    "\t"
    "something on half a Sheet of Paper, and upon Enquiry, I understood she was preparing a "
    "\t"
    "Paper, call\'d, The New-England Courant. On her Right Hand sat English, with a pleasant "
    "\t"
    "smiling Countenance, and handsomely attir\'d; and on her left were seated several Antique "
    "\t"
    "Figures with their Faces vail\'d. I was considerably puzzl\'d to guess who they were, until "
    "\t"
    "one informed me, (who stood beside me,) that those Figures on her left Hand were Latin, "
    "\t"
    "Greek, Hebrew, &c. and that they were very much reserv\'d, and seldom or never unvail\'d "
    "\t"
    "their Faces here, and then to few or none, tho\' most of those who have in this Place "
    "\t"
    "acquir\'d so much Learning as to distinguish them from English, pretended to an intimate "
    "\t"
    "Acquaintance with them. I then enquir\'d of him, what could be the Reason why they "
    "\t"
    "continued vail\'d, in this Place especially: He pointed to the Foot of the Throne, where I "
    "\t"
    "saw Idleness, attended with Ignorance, and these (he informed me) were they, who first "
    "\t"
    "vail\'d them, and still kept them so."
    "\n"
    "Now I observed, that the whole Tribe who entred into the Temple with me, began to climb "
    "\t"
    "the Throne; but the Work proving troublesome and difficult to most of them, they withdrew "
    "\t"
    "their Hands from the Plow, and contented themselves to sit at the Foot, with "
    "\t"
    "Madam Idleness and her Maid Ignorance, until those who were assisted by Diligence and "
    "\t"
    "a docible Temper, had well nigh got up the first Step: But the Time drawing nigh in which "
    "\t"
    "they could no way avoid ascending, they were fain to crave the Assistance of those who "
    "\t"
    "had got up before them, and who, for the Reward perhaps of a Pint of Milk, or a Piece of "
    "\t"
    "Plumb-Cake, lent the Lubbers a helping Hand, and sat them in the Eye of the World, upon "
    "\t"
    "a Level with themselves."
    "\n"
    "The other Step being in the same Manner ascended, and the usual Ceremonies at an "
    "\t"
    "End, every Beetle-Scull seem\'d well satisfy\'d with his own Portion of Learning, tho\' "
    "\t"
    "perhaps he was e\'en just as ignorant as ever. And now the Time of their Departure being "
    "\t"
    "come, they march\'d out of Doors to make Room for another Company, who waited for "
    "\t"
    "Entrance: And I, having seen all that was to be seen, quitted the hall likewise, and went to "
    "\t"
    "make my Observations on those who were just gone out before me."
    "\n"
    "Some I perceiv\'d took to Merchandizing, others to Travelling, some to one Thing, some to "
    "\t"
    "another, and some to Nothing; and many of them from henceforth, for want of Patrimony, "
    "\t"
    "liv\'d as poor as Church Mice, being unable to dig, and asham\'d to beg, and to live by their "
    "\t"
    "Wits it was impossible. But the most Part of the Crowd went along a large beaten Path, "
    "\t"
    "which led to a Temple at the further End of the Plain, call\'d, The Temple of Theology. The "
    "\t"
    "Business of those who were employ\'d in this Temple being laborious and painful, I "
    "\t"
    "wonder\'d exceedingly to see so many go towards it; but while I was pondering this Matter "
    "\t"
    "in my Mind, I spy\'d Pecunia behind a Curtain, beckoning to them with her Hand, which "
    "\t"
    "Sight immediately satisfy\'d me for whose Sake it was, that a great Part of them (I will not "
    "\t"
    "say all) travel\'d that Road. In this Temple I saw nothing worth mentioning, except the "
    "\t"
    "ambitious and fraudulent Contrivances of Plagius, who (notwithstanding he had been "
    "\t"
    "severely reprehended for such Practices before) was diligently transcribing some eloquent "
    "\t"
    "Paragraphs out of Tillotson\'s Works, &c., to embellish his own."
    "\n"
    "Now I bethought my self in my Sleep, that it was Time to be at Home, and as I fancy\'d I "
    "\t"
    "was travelling back thither, I reflected in my Mind on the extream Folly of those Parents, "
    "\t"
    "who, blind to their Childrens Dulness, and insensible of the Solidity of their Skulls, "
    "\t"
    "because they think their Purses can afford it, will needs send them to the Temple of "
    "\t"
    "Learning, where, for want of a suitable Genius, they learn little more than how to carry "
    "\t"
    "themselves handsomely, and enter a Room genteely, (which might as well be acquir\'d at a "
    "\t"
    "Dancing-School,) and from whence they return, after Abundance of Trouble and Charge, "
    "\t"
    "as great Blockheads as ever, only more proud and self-conceited."
    "\n"
    "While I was in the midst of these unpleasant Reflections, Clericus (who with a Book in his "
    "\t"
    "Hand was walking under the Trees) accidentally awak\'d me; to him I related my Dream "
    "\t"
    "with all its Particulars, and he, without much Study, presently interpreted it, assuring "
    "\t"
    "me, That it was a lively Representation of Harvard College, Etcetera. I remain, Sir, Your "
    "\t"
    "Humble Servant,";

const String letter5 = ""
    "Among the many reigning Vices of the Town which may at any Time come under my "
    "\t"
    "Consideration and Reprehension, there is none which I am more inclin\'d to expose than "
    "\t"
    "that of Pride. It is acknowledg\'d by all to be a Vice the most hateful to God and Man. Even "
    "\t"
    "those who nourish it in themselves, hate to see it in others. The proud Man aspires after "
    "\t"
    "Nothing less than an unlimited Superiority over his Fellow-Creatures. He has made "
    "\t"
    "himself a King in Soliloquy; fancies himself conquering the World; and the Inhabitants "
    "\t"
    "thereof consulting on proper Methods to acknowledge his Merit. I speak it to my Shame, I "
    "\t"
    "my self was a Queen from the Fourteenth to the Eighteenth Year of my Age, and govern\'d "
    "\t"
    "the World all the Time of my being govern\'d by my Master. But this speculative Pride may "
    "\t"
    "be the Subject of another Letter: I shall at present confine my Thoughts to what we "
    "\t"
    "call Pride of Apparel. This Sort of Pride has been growing upon us ever since we parted "
    "\t"
    "with our Homespun Cloaths for Fourteen Penny Stuffs, &c. And the Pride of Apparel has "
    "\t"
    "begot and nourish\'d in us a Pride of Heart, which portends the Ruin of Church and "
    "\t"
    "State. Pride goeth before Destruction, and a haughty Spirit before a Fall: And I remember "
    "\t"
    "my late Reverend Husband would often say upon this Text, That a Fall was the natural "
    "\t"
    "Consequence, as well as Punishment of Pride. Daily Experience is sufficient to evince the "
    "\t"
    "Truth of this Observation. Persons of small Fortune under the Dominion of this Vice, "
    "\t"
    "seldom consider their Inability to maintain themselves in it, but strive to imitate their "
    "\t"
    "Superiors in Estate, or Equals in Folly, until one Misfortune comes upon the Neck of "
    "\t"
    "another, and every Step they take is a Step backwards. By striving to appear rich they "
    "\t"
    "become really poor, and deprive themselves of that Pity and Charity which is due to the "
    "\t"
    "humble poor Man, who is made so more immediately by Providence."
    "\n"
    "This Pride of Apparel will appear the more foolish, if we consider, that those airy Mortals, "
    "\t"
    "who have no other Way of making themselves considerable but by gorgeous Apparel, "
    "\t"
    "draw after them Crowds of Imitators, who hate each other while they endeavour after a "
    "\t"
    "Similitude of Manners. They destroy by Example, and envy one another\'s Destruction."
    "\n"
    "I cannot dismiss this Subject without some Observations on a particular Fashion now "
    "\t"
    "reigning among my own Sex, the most immodest and inconvenient of any the Art of "
    "\t"
    "Woman has invented, namely, that of Hoop-Petticoats. By these they are incommoded in "
    "\t"
    "their General and Particular Calling, and therefore they cannot answer the Ends of either "
    "\t"
    "necessary or ornamental Apparel. These monstrous topsy-turvy Mortar-Pieces, are neither "
    "\t"
    "fit for the Church, the Hall, or the Kitchen; and if a Number of them were well mounted on "
    "\t"
    "Noddles-Island, they would look more like Engines of War for bombarding the Town, than "
    "\t"
    "Ornaments of the Fair Sex. An honest Neighbour of mine, happening to be in Town some "
    "\t"
    "time since on a publick Day, inform\'d me, that he saw four Gentlewomen with their Hoops "
    "\t"
    "half mounted in a Balcony, as they withdrew to the Wall, to the great Terror of the Militia, "
    "\t"
    "who (he thinks) might attribute their irregular Volleys to the formidable Appearance of the "
    "\t"
    "Ladies Petticoats."
    "\n"
    "I assure you, Sir, I have but little Hopes of perswading my Sex, by this Letter, utterly to "
    "\t"
    "relinquish the extravagant Foolery, and Indication of Immodesty, in this monstrous Garb of "
    "\t"
    "their\'s; but I would at least desire them to lessen the Circumference of their Hoops, and "
    "\t"
    "leave it with them to consider, Whether they, who pay no Rates or Taxes, ought to take up "
    "\t"
    "more Room in the King\'s High-Way, than the Men, who yearly contribute to the Support of "
    "\t"
    "the Government. I am, Sir, Your Humble Servant,";

const String letter6 = ""
    "It has been the Complaint of many Ingenious Foreigners, who have travell\'d amongst "
    "\t"
    "us, That good Poetry is not to be expected in New-England. I am apt to Fancy, the Reason "
    "\t"
    "is, not because our Countreymen are altogether void of a Poetical Genius, nor yet "
    "\t"
    "because we have not those Advantages of Education which other Countries have, but "
    "\t"
    "purely because we do not afford that Praise and Encouragement which is merited, when "
    "\t"
    "any thing extraordinary of this Kind is produc\'d among us: Upon which Consideration I "
    "\t"
    "have determined, when I meet with a Good Piece of New-England Poetry, to give it a "
    "\t"
    "suitable Encomium, and thereby endeavour to discover to the World some of its Beautys, "
    "\t"
    "in order to encourage the Author to go on, and bless the World with more, and more "
    "\t"
    "Excellent Productions."
    "\n"
    "There has lately appear\'d among us a most Excellent Piece of Poetry, entituled, An Elegy "
    "\t"
    "upon the much Lamented Death of Mrs. Mehitebell Kitel, Wife of Mr. John Kitel of Salem, "
    "\t"
    "&c. It may justly be said in its Praise, without Flattery to the Author, that it is the "
    "\t"
    "most Extraordinary Piece that ever was wrote in New-England. The Language is so soft "
    "\t"
    "and Easy, the Expression so moving and pathetick, but above all, the Verse and Numbers "
    "\t"
    "so Charming and Natural, that it is almost beyond Comparison,"
    "\n"
    "The Muse disdains"
    "\n"
    "Those Links and Chains,"
    "\n"
    "Measures and Rules of vulgar Strains,"
    "\n"
    "And o\'er the Laws of Harmony a Sovereign Queen she reigns."
    "\n"
    "I find no English Author, Ancient or Modern, whose Elegies may be compar\'d with this, in "
    "\t"
    "respect to the Elegance of Stile, or Smoothness of Rhime; and for the affecting Part, I will "
    "\t"
    "leave your Readers to judge, if ever they read any Lines, that would sooner make "
    "\t"
    "them draw their Breath and Sigh, if not shed Tears, than these following."
    "\n"
    "Come let us mourn, for we have lost a Wife, a Daughter, and a Sister, "
    "\t"
    "Who has lately taken Flight, and greatly we have mist her."
    "\n"
    "In another Place,"
    "\n"
    "Some little Time before she yielded up her Breath, "
    "\t"
    "She said, I ne\'er shall hear one Sermon more on Earth. "
    "\t"
    "She kist her Husband some little Time before she expir\'d, "
    "\t"
    "Then lean\'d her Head the Pillow on, just out of Breath and tir\'d. "
    "\n"
    "But the Threefold Appellation in the first Line"
    "\n"
    "a Wife, a Daughter, and a Sister, must not pass unobserved. That Line in the celebrated "
    "\t"
    "Watts, Gunston the Just, the Generous, and the Young, is nothing Comparable to it. The "
    "\t"
    "latter only mentions three Qualifications of one Person who was deceased, which "
    "\t"
    "therefore could raise Grief and Compassion but for One. Whereas the former, (our most "
    "\t"
    "excellent Poet) gives his Reader a Sort of an Idea of the Death of Three Persons, viz. a "
    "\t"
    "Wife, a Daughter, and a Sister, which is Three Times as great a Loss as the Death "
    "\t"
    "of One, and consequently must raise Three Times as much Grief and Compassion in the "
    "\t"
    "Reader."
    "\n"
    "I should be very much straitned for Room, if I should attempt to discover even half the "
    "\t"
    "Excellencies of this Elegy which are obvious to me. Yet I cannot omit one Observation, "
    "\t"
    "which is, that the Author has (to his Honour) invented a new Species of Poetry, which "
    "\t"
    "wants a Name, and was never before known. His Muse scorns to be confin\'d to the old "
    "\t"
    "Measures and Limits, or to observe the dull Rules of Criticks;"
    "\n"
    "Nor Rapin gives her Rules to fly, nor Purcell Notes to sing. Watts."
    "\n"
    "Now \'tis Pity that such an Excellent Piece should not be dignify\'d with a particular Name; "
    "\t"
    "and seeing it cannot justly be called, either Epic, Sapphic, Lyric, or Pindaric, nor any other "
    "\t"
    "Name yet invented, I presume it may, (in Honour and Remembrance of the Dead) be "
    "\t"
    "called the Kitelic. Thus much in the Praise of Kitelic Poetry."
    "\n"
    "It is certain, that those Elegies which are of our own Growth, (and our Soil seldom "
    "\t"
    "produces any other sort of Poetry) are by far the greatest part, wretchedly Dull and "
    "\t"
    "Ridiculous. Now since it is imagin\'d by many, that our Poets are honest, well-meaning "
    "\t"
    "Fellows, who do their best, and that if they had but some Instructions how to govern Fancy "
    "\t"
    "with Judgment, they would make indifferent good Elegies; I shall here subjoin a Receipt "
    "\t"
    "for that purpose, which was left me as a Legacy, (among other valuable Rarities) by my "
    "\t"
    "Reverend Husband. It is as follows,"
    "\n"
    "A RECEIPT to make a New-England Funeral ELEGY."
    "\n"
    "For the Title of your Elegy. Of these you may have enough ready made to your Hands; but "
    "\t"
    "if you should chuse to make it your self, you must be sure not to omit the Words Aetatis "
    "\t"
    "Suae, which will Beautify it exceedingly."
    "\n"
    "For the Subject of your Elegy. Take one of your Neighbours who has lately departed this "
    "\t"
    "Life; it is no great matter at what Age the Party dy\'d, but it will be best if he went away "
    "\t"
    "suddenly, being Kill\'d, Drown\'d, or Froze to Death."
    "\n"
    "Having chose the Person, take all his Virtues, Excellencies, &c. and if he have not "
    "\t"
    "enough, you may borrow some to make up a sufficient Quantity: To these add his last "
    "\t"
    "Words, dying Expressions, &c. if they are to be had; mix all these together, and be sure "
    "\t"
    "you strain them well. Then season all with a Handful or two of Melancholly Expressions, "
    "\t"
    "such as, Dreadful, Deadly, cruel cold Death, unhappy Fate, weeping Eyes, &c. Have "
    "\t"
    "mixed all these Ingredients well, put them into the empty Scull of some young Harvard; "
    "\t"
    "(but in Case you have ne\'er a One at Hand, you may use your own,) there let them "
    "\t"
    "Ferment for the Space of a Fortnight, and by that Time they will be incorporated into a "
    "\t"
    "Body, which take out, and having prepared a sufficient Quantity of double Rhimes, such "
    "\t"
    "as, Power, Flower; Quiver, Shiver; Grieve us, Leave us; tell you, excel you; Expeditions, "
    "\t"
    "Physicians; Fatigue him, Intrigue him; &c. you must spread all upon Paper, and if you can "
    "\t"
    "procure a Scrap of Latin to put at the End, it will garnish it mightily; then having affixed "
    "\t"
    "your Name at the Bottom, with a Moestus Composuit, you will have an Excellent Elegy."
    "\n"
    "N.B. This Receipt will serve when a Female is the Subject of your Elegy, provided you "
    "\t"
    "borrow a greater Quantity of Virtues, Excellencies, &c. Sir, Your Servant,";

final List letters = [letter1, letter2, letter3, letter4, letter5, letter6];
